apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - networkpolicy.yaml
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: forgejo
    namespace: forgejo
    envs:
      - .env
  - name: forgejo-ssh
    namespace: forgejo
    files:
      - signing.pub
