apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 25Gi
