apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-bigquery-exporter
  namespace: prometheus
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus-bigquery-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-bigquery-exporter
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: default
      containers:
        - name: prometheus-bigquery-exporter
          image: prometheus-bigquery-exporter
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: PROMBQ_DATASET
              value: prometheus
            - name: PROMBQ_TABLE
              value: metrics
            - name: PROMBQ_GCP_JSON
              value: /service-account-gcp/service-account-gcp.json
          volumeMounts:
            - mountPath: /service-account-gcp
              name: service-account-gcp
              readOnly: true
          ports:
            - containerPort: 9201
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
      volumes:
        - name: service-account-gcp
          secret:
            secretName: service-account-gcp
