apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: node-exporter
    newName: quay.io/prometheus/node-exporter
    newTag: "v1.9.1"

resources:
  - namespace.yaml
  - stateful_set.yaml
  - service.yaml
