apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: postgres-secret
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
